version: "3.1"

services:
  neo4j:
    image: "neo4j:latest"
    container_name: go-neo4j-crud
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j-standalone
    environment:
      - NEO4J_AUTH=neo4j/test1234

networks:
  neo4j-standalone:
    driver: bridge
